### ISSUE TITLE
Add Monte Carlo examples

### ISSUE THREAD

**Issue by aytekinar** [KTH-AC/ACCESS-Julia#2]
Add Monte Carlo examples covering
- [x] Some parallel programming concepts in Julia,
- [x] IO concepts (saving the results in binary and/or csv formats), and,
- [ ] [`RecipesBase.jl`](https://github.com/JuliaPlots/RecipesBase.jl) integration.

**Comment by aytekinar** [comment]
@neveritt, can  you check the example in your Jupyter or in JuliaBox?

What am I missing? 4 workers, and not even 2x speed-up. Do you think it is the example, or am I doing something stupid?

**Comment by neveritt** [comment]
I think you are doing something stupid, in the first example you do precompilation, for the consecutive ones you don't.

I checked in Jupyter and I got the following timings:
Serial: 6.7 s
parallel: 2.3 s
simulate_shared: 2.2 s

**Comment by aytekinar** [comment]
thanks for checking for me! actually, I am not doing that stupid thing --- if you look at the output counts, it jumps from 10 and 17 to 12 and 19, leaving 11 and 18 as precompilation outputs :)

weird... still, 2.2 vs 6.7 sec is nice --- 3x speed-up is ok. I will rewrite them a bit different, and see if it changes anything :)

any suggestions? how do you think the example is?

**Comment by neveritt** [comment]
I think it is good. 
You need to explain the macros @sync @async @parallel etcetera, but that you can do when you speak
