### ISSUE TITLE
Add cheatsheet

### ISSUE THREAD

**Issue by aytekinar** [KTH-AC/ACCESS-Julia#3]
Maybe we can add a cheat sheet like [this](http://cheatsheets.quantecon.org/). Actually, I had a pdf file covering similar topics, but I couldn't find it :( Yet, this one looks good enough. What do you think @neveritt ? Whatever we do, we should not forget to mention the difference between vectors and matrices (i.e., `x.'*A*x` yields a vector where as `dot(x, A*x)` or `x\cdot<TAB>(A*x)` yields a scalar).

**Comment by neveritt** [comment]
I think it would be good just to play around with those things in the pdf for a few minutes just give people a feeling that it is the same as Matlab first.

Then, perhaps we can bring up a few of the pitfalls in the differences in 
http://docs.julialang.org/en/release-0.4/manual/noteworthy-differences/
as well as the example you mentioned.

This is a nice read, but the topics might be a bit too much for the first time user:
http://www.stochasticlifestyle.com/7-julia-gotchas-handle/

**Comment by neveritt** [comment]
@aytekinar could you please have a look?

**Comment by aytekinar** [comment]
looks nice. two minor comments:

1.  `b = 2. # double precision floating point`, `b = 2.0f # single precision floating point`, if needed,
2.  `isa(D, Matrix) # this is false`, `isa(D, AbstractMatrix) # this is true`.

We can state the above two verbally, tho. If you say `Abstract`ions are too much, then we can ignore this --- yet, it might be good to know that `Vector`s and `Matrix`s are dense versions of their abstractions.

Uhm... Shall we name this as `0-Julia-basics` or are you planning to merge them? What do you think?

**Comment by neveritt** [comment]
Thanks!
That was a good suggestion with 0-Julia-basics, didn't think of it.

Both are good points and I will include them.
